# Generated by Django 3.2.4 on 2021-09-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('stockdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=280)),
                ('pub_date', models.DateTimeField(db_index=True, verbose_name='date published')),
                ('isSubMemo', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.player')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdb.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='MemoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=32)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.memo')),
            ],
        ),
        migrations.CreateModel(
            name='subMemo',
            fields=[
                ('memo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agora.memo')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agora.memo')),
            ],
            bases=('agora.memo',),
        ),
    ]
