# Generated by Django 3.2.4 on 2021-09-05 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.JSONField(default=portfolio.models.Player.portfolio_default, verbose_name='portfolio')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(db_index=True, verbose_name='date published')),
                ('ticker', models.CharField(max_length=16)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('validation', models.CharField(max_length=16, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.player')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('asset', models.FloatField(null=True)),
                ('quant', models.JSONField(null=True)),
                ('amount', models.JSONField(null=True)),
                ('code', models.IntegerField(db_index=True, default=0, verbose_name='0:no asset,1:normal day,2:end of month,3:today')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.player')),
            ],
        ),
    ]
