# Generated by Django 3.2.4 on 2021-09-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sector', models.CharField(default='', max_length=50)),
                ('exchange', models.CharField(default='', max_length=16)),
                ('currency', models.CharField(default='', max_length=16)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_date', models.DateTimeField(null=True, verbose_name='last updated date')),
                ('last_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DayPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Open', models.FloatField(default=0, null=True)),
                ('High', models.FloatField(default=0, null=True)),
                ('Low', models.FloatField(default=0, null=True)),
                ('Close', models.FloatField(default=0, null=True)),
                ('Volume', models.FloatField(null=True)),
                ('Dividends', models.FloatField(null=True)),
                ('Split', models.IntegerField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdb.ticker')),
            ],
        ),
    ]
